#!/bin/bash

template="$1"

if [ "$template" = 'array' ]; then
        name="$2"
        datatype="$3"

        sed -e "s/NAME/$name/g" \
            -e "s/TYPE/$datatype/g" <$template.h >"$name.h"

        sed -e "s/NAME/$name/g" \
            -e "s/TYPE/$datatype/g" <$template.c >"$name.c"
elif [ -n "$template" ]; then
        echo invalid template: $template
else
        echo no template given
fi
