#!/bin/bash

template="$1"

if [ "$template" = 'array' ] || \
   [ "$template" = 'rbuf' ] || \
   [ "$template" = 'dlist' ]; then
        name="$2"
        datatype="$3"

        sed -e "s/NAME/$name/g" \
            -e "s/TYPE/$datatype/g" <$template.h >"$name.h"

        sed -e "s/NAME/$name/g" \
            -e "s/TYPE/$datatype/g" <$template.c >"$name.c"
elif [ "$template" = 'bitset' ]; then
        name="$2"
        datatype="$3"
        bits_per_idx="$4"

        sed -e "s/NAME/$name/g" \
            -e "s/TYPE/$datatype/g" \
            -e "s/BITS/$bits_per_idx/g" <$template.h >"$name.h"

        sed -e "s/NAME/$name/g" \
            -e "s/TYPE/$datatype/g" \
            -e "s/BITS/$bits_per_idx/g" <$template.c >"$name.c"
elif [ "$template" = 'slist_hash_map' ]; then
        name="$2"
        keytype="$3"
        valuetype="$4"
        keycmp="$5"
        hashfn="$6"

        sed -e "s/NAME/$name/g" \
            -e "s/KEY_T/$keytype/g" \
            -e "s/VALUE_T/$valuetype/g" \
            -e "s/KEY_CMP/$keycmp/g" \
            -e "s/HASH_FN/$hashfn/g" <$template.h >"$name.h"

        sed -e "s/NAME/$name/g" \
            -e "s/KEY_T/$keytype/g" \
            -e "s/VALUE_T/$valuetype/g" \
            -e "s/KEY_CMP/$keycmp/g" \
            -e "s/HASH_FN/$hashfn/g" <$template.c >"$name.c"
elif [ "$template" = 'rb_map' ]; then
        name="$2"
        keytype="$3"
        valuetype="$4"
        keycmp="$5"

        sed -e "s/NAME/$name/g" \
            -e "s/KEY_T/$keytype/g" \
            -e "s/VALUE_T/$valuetype/g" \
            -e "s/KEY_CMP/$keycmp/g" <$template.h >"$name.h"

        sed -e "s/NAME/$name/g" \
            -e "s/KEY_T/$keytype/g" \
            -e "s/VALUE_T/$valuetype/g" \
            -e "s/KEY_CMP/$keycmp/g" <$template.c >"$name.c"
elif [ "$template" = 'sorted_slist' ]; then
        name="$2"
        datatype="$3"
        cmpfn="$4"

        sed -e "s/NAME/$name/g" \
            -e "s/CMP_FN/$cmpfn/g" \
            -e "s/TYPE/$datatype/g" <$template.h >"$name.h"

        sed -e "s/NAME/$name/g" \
            -e "s/CMP_FN/$cmpfn/g" \
            -e "s/TYPE/$datatype/g" <$template.c >"$name.c"
elif [ -n "$template" ]; then
        echo invalid template: $template
else
        echo no template given
fi
